# **Installations**

In [ ]:
!pip install ultralytics

In [ ]:
from google.colab import drive
from ultralytics import YOLO
import numpy as np
np.random.seed(42)

drive.mount('/content/drive')

Mounted at /content/drive


# **Entraînement**

## **A partir de zéro**

In [ ]:
model = YOLO('yolov8x-cls.pt')
results = model.train(data='/content/drive/MyDrive/Cpred/Augmented_data_split_2000', epochs=35, imgsz=416, seed=0)

Ultralytics YOLOv8.1.2 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=classify, mode=train, model=yolov8x-cls.pt, data=/content/drive/MyDrive/Cpred/Augmented_data_split_2000, epochs=35, time=None, patience=50, batch=16, imgsz=416, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_l

train: Scanning /content/drive/MyDrive/Cpred/Augmented_data_split_2000/train... 8664 images, 0 corrupt: 100%|██████████| 8664/8664 [1:34:20<00:00,  1.53it/s]


train: New cache created: /content/drive/MyDrive/Cpred/Augmented_data_split_2000/train.cache


val: Scanning /content/drive/MyDrive/Cpred/Augmented_data_split_2000/validation... 670 images, 0 corrupt:  24%|██▍       | 670/2800 [03:35<11:25,  3.11it/s]


KeyboardInterrupt: 

## **A partir d'un entraînement non terminé**

In [ ]:
#model = YOLO('/content/drive/MyDrive/Cpred/Reduced_postprocessed_split_by_classes_train_test_val/runs/classify/train/weights/last.pt')
#results = model.train(resume=True)

In [ ]:
!cp -r yolov8n.pt /content/drive/MyDrive/Cpred/Augmented_data_split_2000
!cp -r yolov8x-cls.pt /content/drive/MyDrive/Cpred/Augmented_data_split_2000

In [ ]:
!cp -r runs /content/drive/MyDrive/Cpred/Augmented_data_split_2000

# **Travailler sur un modèle entraîné**

In [ ]:
model = YOLO('/content/drive/MyDrive/Cpred/Augmented_data_split_2000/runs/classify/train2/weights/best.pt')

# **Metrics**

In [ ]:
metrics = model.val()

Ultralytics YOLOv8.1.2 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
YOLOv8x-cls summary (fused): 133 layers, 56132167 parameters, 0 gradients, 153.8 GFLOPs
train: /content/drive/MyDrive/Cpred/Augmented_data_split_2000/train... found 8664 images in 7 classes ✅ 
val: /content/drive/MyDrive/Cpred/Augmented_data_split_2000/validation... found 2800 images in 7 classes ✅ 
test: /content/drive/MyDrive/Cpred/Augmented_data_split_2000/test... found 2800 images in 7 classes ✅ 


val: Scanning /content/drive/MyDrive/Cpred/Augmented_data_split_2000/validation... 2800 images, 0 corrupt: 100%|██████████| 2800/2800 [00:00<?, ?it/s]
               classes   top1_acc   top5_acc:   1%|          | 2/175 [00:09<11:33,  4.01s/it]


100%|██████████| 755k/755k [00:00<00:00, 26.5MB/s]
               classes   top1_acc   top5_acc: 100%|██████████| 175/175 [07:46<00:00,  2.67s/it]


                   all      0.953      0.999
Speed: 0.2ms preprocess, 15.3ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to runs/classify/val


In [ ]:
!cp -r runs/classify/val /content/drive/MyDrive/Cpred/Augmented_data_split_2000/runs/classify

In [ ]:
print(metrics)

ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7ad924836710>
curves: []
curves_results: []
fitness: 0.9762499928474426
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.9532142877578735, 'metrics/accuracy_top5': 0.9992856979370117, 'fitness': 0.9762499928474426}
save_dir: PosixPath('runs/classify/val')
speed: {'preprocess': 0.18790321690695627, 'inference': 15.335840667997088, 'loss': 0.0008078983851841519, 'postprocess': 0.000629425048828125}
task: 'classify'
top1: 0.9532142877578735
top5: 0.9992856979370117


In [ ]:
# Accéder à la matrice de confusion
confusion_matrix = metrics.confusion_matrix

# Obtenir la matrice NumPy
matrix_values = confusion_matrix.matrix

# Afficher la matrice de confusion normalisée et arrondie
print("Matrice de confusion :")
print(matrix_values)

print(matrix_values[0][0])

Matrice de confusion :
[[        396           1           6           0           4           3           0]
 [          0         394           4           0           3           2           0]
 [          2           3         366           0          10          12           0]
 [          0           0           0         399           0           1           0]
 [          2           1          22           1         366          34           0]
 [          0           1           2           0          17         348           0]
 [          0           0           0           0           0           0         400]]
396.0


In [ ]:
results = model.predict('/content/drive/MyDrive/Cpred/Augmented_data_split_2000/test/df')

In [ ]:
import numpy as np

# Matrice de confusion normalisée pour chaque classe
conf_matrix_pre = np.array([
    [0.68, 0.03, 0.02, 0.00, 0.03, 0.00, 0.00],
    [0.02, 0.87, 0.01, 0.00, 0.01, 0.00, 0.00],
    [0.12, 0.01, 0.81, 0.11, 0.04, 0.02, 0.00],
    [0.02, 0.01, 0.02, 0.72, 0.00, 0.00, 0.00],
    [0.14, 0.03, 0.09, 0.06, 0.73, 0.03, 0.00],
    [0.02, 0.05, 0.06, 0.11, 0.23, 0.94, 0.05],
    [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.95]
])

conf_matrix_post1 = np.array([
    [0.78, 0.01, 0.00, 0.00, 0.01, 0.00, 0.00],
    [0.06, 0.88, 0.02, 0.06, 0.01, 0.00, 0.00],
    [0.08, 0.00, 0.78, 0.00, 0.10, 0.02, 0.00],
    [0.00, 0.00, 0.02, 0.78, 0.00, 0.00, 0.00],
    [0.00, 0.04, 0.10, 0.06, 0.67, 0.02, 0.00],
    [0.08, 0.06, 0.08, 0.11, 0.23, 0.96, 0.09],
    [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.91]
])

conf_matrix_post2 = np.array([
    [0.60, 0.04, 0.02, 0.00, 0.01, 0.00, 0.00],
    [0.14, 0.88, 0.01, 0.00, 0.01, 0.00, 0.00],
    [0.04, 0.03, 0.81, 0.00, 0.09, 0.02, 0.00],
    [0.04, 0.00, 0.01, 0.78, 0.00, 0.00, 0.00],
    [0.10, 0.03, 0.08, 0.00, 0.66, 0.03, 0.00],
    [0.08, 0.03, 0.07, 0.22, 0.23, 0.95, 0.09],
    [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.91]
])

labels = ["akiec", "bcc", "bkl", "df", "mel", "nv", "vasc"]

def calculate_f1_score(conf_matrix, label_index):
    tp = conf_matrix[label_index, label_index]
    fp = np.sum(conf_matrix[:, label_index]) - tp
    fn = np.sum(conf_matrix[label_index, :]) - tp

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0

    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    return f1

def calculate_balanced_accuracy(conf_matrix):
    num_classes = conf_matrix.shape[0]

    balanced_accuracies = []

    for i in range(num_classes):
        tp = conf_matrix[i, i]
        fn = np.sum(conf_matrix[i, :]) - tp

        class_accuracy = tp / (tp + fn) if (tp + fn) > 0 else 0
        balanced_accuracies.append(class_accuracy)

    balanced_accuracy = np.mean(balanced_accuracies)
    return balanced_accuracy

f1_scores = [calculate_f1_score(conf_matrix_post2, i) for i in range(len(labels))]

for label, f1 in zip(labels, f1_scores):
    print(f"F1-score for class {label}: {f1:.4f}")
average_f1_score = np.mean(f1_scores)
print(f"Average F1-score: {average_f1_score:.4f}")

balanced_accuracy_pre = calculate_balanced_accuracy(conf_matrix_pre)
balanced_accuracy_post1 = calculate_balanced_accuracy(conf_matrix_post1)
balanced_accuracy_post2 = calculate_balanced_accuracy(conf_matrix_post2)


print(f"Balanced Accuracy: {balanced_accuracy_pre:.4f}")
print(f"Balanced Accuracy: {balanced_accuracy_post1:.4f}")
print(f"Balanced Accuracy: {balanced_accuracy_post2:.4f}")


F1-score for class akiec: 0.7186
F1-score for class bcc: 0.8585
F1-score for class bkl: 0.8141
F1-score for class df: 0.8525
F1-score for class mel: 0.6947
F1-score for class nv: 0.7116
F1-score for class vasc: 0.9529
Average F1-score: 0.8004
Balanced Accuracy: 0.8336
Balanced Accuracy: 0.8499
Balanced Accuracy: 0.8288
